import type { Product } from "./types";

export const demoProducts: Product[] = [
  {
    id: "demo-20box",
    slug: "20-box-standard-usato",
    title: "Container 20' Box Standard",
    size: "20'",
    type: "Box Standard",
    condition: "Usato · Ottime condizioni strutturali",
    location: "Salerno",
    price: null,
    vatIncluded: false,
    availability: null,
    description: "Container marittimo usato da 20 piedi, impermeabile e pronto all'uso. Ideale per magazzino, deposito attrezzi, trasporto, cantieri e numerosi utilizzi logistici o industriali.",
    imageUrl: null,
    lengthM: 6.06,
    widthM: 2.44,
    heightM: 2.59,
    volumeM3: 33
  },
  {
    id: "demo-40box",
    slug: "40-box-standard-usato",
    title: "Container 40' Box Standard",
    size: "40'",
    type: "Box Standard",
    condition: "Usato · Ottime condizioni strutturali",
    location: "Salerno",
    price: null,
    vatIncluded: false,
    availability: null,
    description: "Container marittimo usato da 40 piedi con grande capacità interna. Una soluzione robusta per stoccaggio, deposito, logistica, trasporti e trasformazioni.",
    imageUrl: null,
    lengthM: 12.19,
    widthM: 2.44,
    heightM: 2.59,
    volumeM3: 67
  },
  {
    id: "demo-40hc",
    slug: "40-high-cube-usato",
    title: "Container 40' High Cube",
    size: "40' HC",
    type: "High Cube",
    condition: "Usato · Ottime condizioni strutturali",
    location: "Salerno",
    price: null,
    vatIncluded: false,
    availability: null,
    description: "Container 40 piedi High Cube con altezza maggiorata e circa 76 m³ di volume. Ideale quando serve più capacità per stoccaggio, logistica o progetti di trasformazione.",
    imageUrl: null,
    lengthM: 12.19,
    widthM: 2.44,
    heightM: 2.90,
    volumeM3: 76
  },
  {
    id: "demo-reefer",
    slug: "container-reefer-refrigerato",
    title: "Container Reefer Refrigerato",
    size: "REEFER",
    type: "Refrigerato",
    condition: "Usato · Disponibilità su richiesta",
    location: "Salerno",
    price: null,
    vatIncluded: false,
    availability: null,
    description: "Container frigoriferi e refrigerati per trasporto e stoccaggio di prodotti a temperatura controllata, oltre che per specifici impieghi industriali e logistici.",
    imageUrl: null
  },
  {
    id: "demo-office",
    slug: "container-uso-ufficio",
    title: "Container uso Ufficio",
    size: "UFFICIO",
    type: "Allestito",
    condition: "Pronto all'uso · Disponibilità su richiesta",
    location: "Salerno",
    price: null,
    vatIncluded: false,
    availability: null,
    description: "Container allestiti per uso ufficio, ideali come uffici di cantiere, locali operativi, spogliatoi o strutture temporanee per aziende e cantieri.",
    imageUrl: null
  }
];
